name: Assignment 1

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Save test results
        run: echo "Tests completed on Node.js ${{ matrix.node-version }}" > test-report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.node-version }}
          path: test-report.txt

  deploy_qa:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report-16.x
          path: ./qa-report
      - name: Simulate QA Deploy
        run: echo "Deploying to QA environment..."

  deploy_prod:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report-16.x
          path: ./prod-report
      - name: Simulate Production Deploy
        run: echo "Deploying to Production environment..."
