name: Assignment
on: push

jobs:
  build: 
    runs-on: ubuntu-latest

  steps:
    - name: check
      uses: actions/checkout@v2

    - name: Make run.sh executable
      run: chmod +x run.sh

    - name: Run Script
      run: ./run.sh  

    - name: run Script
      uses: bash run.sh


